import type { CashTransactionDto } from '@contracts/cash/cash-transaction.types'
import { toCashTransaction } from '@domain/cash/cash-transaction.mapper'
import type { CashTransaction } from '@domain/cash/cash-transaction.model'
import { Translation } from '@resetshop/angular-core/i18n/translation'
import { clearAllMocks, fn } from '@resetshop/util/test-utils'
import { render, screen } from '@testing-library/angular'
import userEvent from '@testing-library/user-event'
import { createMockCashTransactionDto, createMockConceptDto } from '../cash.mock'
import { cashTranslation } from '../cash.testing'
import { CashTransactionDetails } from './cash-transaction-details'

describe('CashTransactionDetails', () => {
	beforeEach(() => {
		clearAllMocks()
	})

	async function renderDetails(
		overrides: Partial<CashTransactionDto> | null,
		inputs: { canManage?: boolean; loading?: boolean } = {},
	) {
		const deleteRequested = fn<[], void>()
		const editRequested = fn<[CashTransaction], void>()
		const transaction = overrides ? toCashTransaction(createMockCashTransactionDto(overrides)) : null
		await render(CashTransactionDetails, {
			inputs: { transaction, ...inputs },
			on: { deleteRequested, editRequested },
			providers: [{ provide: Translation, useValue: cashTranslation }],
		})
		return { deleteRequested, editRequested }
	}

	it('should invite to select a transaction when none is selected', async () => {
		await renderDetails(null)

		expect(screen.getByText('Select a transaction from the table to see its details.')).toBeInTheDocument()
	})

	it('should show a loading status while the transaction loads', async () => {
		await renderDetails(null, { loading: true })

		expect(screen.getByRole('status')).toHaveTextContent('Loading the transaction...')
	})

	it('should show concept, subconcept, amount and note of the transaction', async () => {
		await renderDetails({ id: 42, amount: '1500.00', note: 'Venta de mostrador' })

		expect(screen.getByText('42')).toBeInTheDocument()
		expect(screen.getByText('Ventas')).toBeInTheDocument()
		expect(screen.getByText('Venta de accesorios')).toBeInTheDocument()
		expect(screen.getByText('$ 1.500,00')).toBeInTheDocument()
		expect(screen.getByText('Venta de mostrador')).toBeInTheDocument()
	})

	it('should list every payment with its method', async () => {
		await renderDetails({
			payments: [
				{
					amount: '1000.00',
					paymentMethod: { id: 1, description: 'Efectivo', allowsInstallments: false, installments: [] },
				},
				{
					amount: '500.00',
					paymentMethod: { id: 4, description: 'Transferencia', allowsInstallments: false, installments: [] },
				},
			],
		})

		expect(screen.getByText('Efectivo - $ 1.000,00')).toBeInTheDocument()
		expect(screen.getByText('Transferencia - $ 500,00')).toBeInTheDocument()
	})

	it('should label an income as Income and an expense as Expense', async () => {
		await renderDetails({})
		expect(screen.getByText('Income')).toBeInTheDocument()
	})

	it('should label an expense as Expense', async () => {
		await renderDetails({
			concept: createMockConceptDto({ transactionType: { id: 0, description: 'Egreso' } }),
		})

		expect(screen.getByText('Expense')).toBeInTheDocument()
	})

	it('should show the associated operation', async () => {
		await renderDetails({ operation: { id: 7, description: 'Reparación' } })

		expect(screen.getByText('Reparación #7')).toBeInTheDocument()
	})

	it('should show a placeholder for an empty note', async () => {
		await renderDetails({ note: '' })

		expect(screen.getByText('No note')).toBeInTheDocument()
	})

	it('should show the author of the transaction', async () => {
		await renderDetails({})

		expect(screen.getByText('clerk')).toBeInTheDocument()
	})

	it('should hide the actions from users that cannot manage the register', async () => {
		await renderDetails({}, { canManage: false })

		expect(screen.queryByRole('button', { name: 'Edit' })).not.toBeInTheDocument()
		expect(screen.queryByRole('button', { name: 'Delete' })).not.toBeInTheDocument()
	})

	it('should request editing the transaction for managers', async () => {
		const { editRequested } = await renderDetails({ id: 42 }, { canManage: true })

		await userEvent.click(screen.getByRole('button', { name: 'Edit' }))

		expect(editRequested.calls).toHaveLength(1)
		expect(editRequested.calls[0][0].id).toBe(42)
	})

	it('should not offer editing a transaction generated by the system', async () => {
		const parent = createMockConceptDto({ userAssignable: false })
		await renderDetails({ concept: createMockConceptDto({ parent }) }, { canManage: true })

		expect(screen.queryByRole('button', { name: 'Edit' })).not.toBeInTheDocument()
		expect(screen.getByRole('button', { name: 'Delete' })).toBeInTheDocument()
	})

	it('should request the deletion', async () => {
		const { deleteRequested } = await renderDetails({}, { canManage: true })

		await userEvent.click(screen.getByRole('button', { name: 'Delete' }))

		expect(deleteRequested.calls).toHaveLength(1)
	})
})
