import { Component } from '@angular/core'
import { TestBed } from '@angular/core/testing'
import { ActivatedRoute, convertToParamMap, provideRouter, Router } from '@angular/router'
import type { CashTransactionRequest } from '@contracts/cash/cash-transaction.types'
import { CashConceptApi } from '@providers/cash-concept/cash-concept.interface'
import { CashApi } from '@providers/cash/cash.interface'
import {
	createMockCashTransactionDto,
	createMockConceptDto,
	createMockPaymentMethodDto,
} from '@providers/cash/cash.mock'
import { provideCashTestEnvironment, seedSession } from '@providers/cash/cash.testing'
import { PaymentMethodApi } from '@providers/payment-method/payment-method.interface'
import {
	advanceTimersByTimeAsync,
	clearAllMocks,
	fn,
	type MockFn,
	spyOn,
	useFakeTimers,
	useRealTimers,
} from '@resetshop/util/test-utils'
import { CashStore } from '@store/cash/cash.store'
import { UIStore } from '@store/ui/ui.store'
import { fireEvent, render, screen } from '@testing-library/angular'
import { NEVER, of, throwError } from 'rxjs'
import CashEdit from './cash-edit'

@Component({ selector: 'app-blank', standalone: true, template: '' })
class Blank {}

describe('CashEdit', () => {
	let cashApiMock: Record<keyof CashApi, MockFn>
	let conceptApiMock: Record<keyof CashConceptApi, MockFn>
	let paymentMethodApiMock: Record<keyof PaymentMethodApi, MockFn>

	const parent = createMockConceptDto({ id: 1, description: 'Ventas', parent: null })
	const child = createMockConceptDto({ id: 11, description: 'Accesorios', parent })
	const tree = [{ ...parent, children: [child] }]
	const transaction = createMockCashTransactionDto({ id: 7, concept: child, note: 'Venta de mostrador' })

	beforeEach(() => {
		useFakeTimers()
		clearAllMocks()
		spyOn(console, 'error')
		seedSession()

		cashApiMock = {
			getAll: fn(),
			getById: fn(),
			create: fn(),
			update: fn(),
			remove: fn(),
			open: fn(),
			close: fn(),
		}
		conceptApiMock = { getAll: fn(), create: fn(), update: fn(), enable: fn(), disable: fn() }
		paymentMethodApiMock = { getAll: fn() }

		cashApiMock.getAll.mockReturnValue(of([]))
		cashApiMock.getById.mockReturnValue(of(transaction))
		conceptApiMock.getAll.mockReturnValue(of(tree))
		paymentMethodApiMock.getAll.mockReturnValue(of([createMockPaymentMethodDto()]))
	})

	afterEach(() => {
		useRealTimers()
	})

	async function renderPage() {
		const view = await render(CashEdit, {
			providers: [
				provideRouter([{ path: 'dashboard/cash', component: Blank }]),
				{ provide: ActivatedRoute, useValue: { snapshot: { paramMap: convertToParamMap({ id: '7' }) } } },
				CashStore,
				...provideCashTestEnvironment({
					cashApi: cashApiMock,
					conceptApi: conceptApiMock,
					paymentMethodApi: paymentMethodApiMock,
				}),
			],
		})
		TestBed.tick()
		await advanceTimersByTimeAsync(1000)
		view.fixture.detectChanges()
		return view
	}

	it('should load the transaction of the route and prefill the form', async () => {
		await renderPage()

		expect(cashApiMock.getById.calls[0]).toEqual([7])
		expect(screen.getByRole('heading', { name: 'Edit transaction' })).toBeInTheDocument()
		expect(screen.getByLabelText(/^Note/)).toHaveValue('Venta de mostrador')
		expect(screen.getByLabelText('Amount')).toHaveValue(1500)
	})

	it('should show a loading status while the transaction loads', async () => {
		cashApiMock.getById.mockReturnValue(NEVER)

		await render(CashEdit, {
			providers: [
				provideRouter([]),
				{ provide: ActivatedRoute, useValue: { snapshot: { paramMap: convertToParamMap({ id: '7' }) } } },
				CashStore,
				...provideCashTestEnvironment({
					cashApi: cashApiMock,
					conceptApi: conceptApiMock,
					paymentMethodApi: paymentMethodApiMock,
				}),
			],
		})

		expect(screen.getByRole('status')).toHaveTextContent('Loading...')
	})

	it('should show the error when the transaction cannot be loaded', async () => {
		cashApiMock.getById.mockReturnValue(throwError(() => new Error('boom')))

		await renderPage()

		expect(screen.getByRole('alert')).toHaveTextContent('The transaction could not be loaded.')
		expect(screen.queryByLabelText('Amount')).not.toBeInTheDocument()
	})

	it('should explain that a system generated transaction cannot be edited', async () => {
		const systemParent = createMockConceptDto({ id: 1, userAssignable: false, parent: null })
		cashApiMock.getById.mockReturnValue(
			of(createMockCashTransactionDto({ id: 7, concept: createMockConceptDto({ id: 11, parent: systemParent }) })),
		)

		await renderPage()

		expect(screen.getByRole('status')).toHaveTextContent(
			'This transaction was generated by the system and cannot be edited.',
		)
		expect(screen.queryByLabelText('Amount')).not.toBeInTheDocument()
	})

	it('should explain that a transaction whose concept is no longer assignable cannot be edited', async () => {
		conceptApiMock.getAll.mockReturnValue(of([]))

		await renderPage()

		expect(screen.getByText('This transaction was generated by the system and cannot be edited.')).toBeInTheDocument()
	})

	it('should send the edited transaction with its id', async () => {
		cashApiMock.update.mockReturnValue(of([1]))
		await renderPage()

		fireEvent.input(screen.getByLabelText(/^Note/), { target: { value: 'Nota corregida del mostrador' } })
		TestBed.tick()
		fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
		TestBed.tick()

		const [request, user] = cashApiMock.update.calls[0] as [CashTransactionRequest, { userName: string }]
		expect(request.id).toBe(7)
		expect(request.note).toBe('Nota corregida del mostrador')
		expect(request.concept.id).toBe(11)
		expect(user.userName).toBe('clerk')
	})

	it('should confirm with a toast and go back to the cash register after updating', async () => {
		cashApiMock.update.mockReturnValue(of([1]))
		await renderPage()

		fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
		TestBed.tick()
		await advanceTimersByTimeAsync(0)

		expect(TestBed.inject(UIStore).notifications()).toEqual([
			expect.objectContaining({ type: 'success', message: 'Transaction updated successfully.' }),
		])
		expect(TestBed.inject(Router).url).toBe('/dashboard/cash')
	})

	it('should keep the form and show the failure inline when updating fails', async () => {
		cashApiMock.update.mockReturnValue(throwError(() => new Error('boom')))
		await renderPage()

		fireEvent.click(screen.getByRole('button', { name: 'Save changes' }))
		TestBed.tick()

		expect(screen.getByRole('alert')).toHaveTextContent('The transaction could not be updated.')
		expect(TestBed.inject(Router).url).toBe('/')
	})

	it('should go back to the cash register when cancelling', async () => {
		await renderPage()

		fireEvent.click(screen.getByRole('button', { name: 'Cancel' }))
		await advanceTimersByTimeAsync(0)

		expect(TestBed.inject(Router).url).toBe('/dashboard/cash')
	})
})
